name: light_bmi_calculator
description: "Simple BMI Calculator for mobile devices"
publish_to: "none"
version: 1.1.0+4

environment:
  sdk: ^3.5.4

dependencies:
  animate_do: ^4.2.0
  bloc: ^9.2.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_dotenv: ^6.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.2
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  purchases_flutter: ^9.11.0
  purchases_ui_flutter: ^9.11.0
  syncfusion_flutter_core: ^32.1.25
  syncfusion_flutter_gauges: ^32.1.25
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.3
  in_app_review: ^2.0.11

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Akayatelivigala
      fonts:
        - asset: assets/fonts/akayatelivigala_regular.ttf
  assets:
    - assets/images/
    - assets/images/icons/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/icon_bright.png"
  image_path_ios: "assets/images/icons/icon_bright.png"
  image_path_ios_dark_transparent: "assets/images/icons/icon_dark.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
